### ISSUE TITLE
Delete Request Function should take filePath string?

### ISSUE THREAD

**Issue by Nikster3k** [42Webserver/42-Vienna-Webserv#51]
Should the deleteRequest function take the filepath string? Because if we have uri "/delete/" and we have an index file for that location should we first do our filepath stuff and have "{root}/index.file" and try to delete this file?

https://github.com/42Webserver/42-Vienna-Webserv/blob/9f11f972579caa4d947689053b2313e7e64787da/Response.cpp#L264-L282

**Comment by Nikster3k** [comment]
I think "root" + "uri" is also wrong because when we have location "/delete/file.txt" we want "<root>/file.txt" and not "<root>/delete/file.txt"

**Comment by Nikster3k** [comment]
Changed it on my PathInfo branch. But does it make sense if we call delete on a location/dir uri="/directory/" that we delete index file if that location has one? I think its okay

**Comment by windchaser-surf** [comment]
how is it possible, that we delete index file?

**Comment by Nikster3k** [comment]
Because if we call delete on uri="/dir/" we do our filepath checking and filepath will end up being "{root}/{indexfile}".

**Comment by windchaser-surf** [comment]
ah ok. yeah. I mean we can handle like this. but what happen if we get a delete request with uri /{root}/[anyfile.txt}, and we do not found this file? we are also deleting index?

**Comment by Nikster3k** [comment]
Will be closed with #50
