### ISSUE TITLE
Confing listen

### ISSUE THREAD

**Issue by Nikster3k** [42Webserver/42-Vienna-Webserv#52]
I think it is possible to have "listen example.com:8080" in the config file.
We have to check with nginx.
Because you can use getaddrinfo and put in "example.com" and if "/etc/hosts" has an entry for that domain it will return the corresponding ip

**Comment by windchaser-surf** [comment]
Nginx, try to bind all ip-adress
for example if we have www.google.com => then it converts to the ip-adress => and bind fails. 
if we have nothing.com => it doesn't find the host. 
so we don't have to check if there is an syntax error at listen. We just split host:port, 
check with getaddrinfo, and if error_code == 0, we try to bind
